# Generated by Django 4.1 on 2022-09-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('01', 'Personalized'), ('02', 'Toys&Gifts'), ('03', 'Stationary')], default='01', max_length=2),
            preserve_default=False,
        ),
    ]
