# Generated by Django 4.1 on 2022-11-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
